### ISSUE TITLE
Annotate non-state changing functions with 'constant'

### ISSUE THREAD

**Issue by esques** [Registereth/RedditRegistry#1]
Solidity provides the `constant` keyword to mark read-only functions, it should be used

https://github.com/RedditRegistereth/RedditRegistry/blob/master/contracts/RedditRegister.sol#L38
https://github.com/RedditRegistereth/RedditRegistry/blob/master/contracts/RedditRegister.sol#L43

**Comment by adamdossa** [comment]
added
